steps:
  - command: 'xcodebuild test -project x.xcodeproj -scheme tests'

  - command: 'xcodebuild clean build -project x.xcodeproj -arch arm64 -scheme x -configuration Release -derivedDataPath ./xcode GCC_PREPROCESSOR_DEFINITIONS="BUILD_NUMBER=\$BUILDKITE_BUILD_NUMBER"'
    artifact_paths: 'xcode/Build/Products/**/*'
